function Number()
{
  this.x=random(width);
  this.y=random(height+200)-100;
  if(random()>.5)
    this.val=1;
  else
    this.val=0;
  this.speed=random(5)+1;
  this.fall=function()
  {
    if(this.y>height+width/25)
      this.y=-width/25;
    textAlign(CENTER,CENTER);
    noStroke();
    fill(0,255,0);
    textSize(width/15)
    text(this.val,this.x,this.y);
    this.y+=this.speed;
  }
}
